# Faces use the 16 terminal palette slots (fg=N/bg=N), so ble.sh follows whatever colors the
# active Omarchy theme sets, live, including in shells that were already open.
# Slots: 0 black, 1 red, 2 green, 3 yellow, 4 blue, 5 magenta, 6 cyan, 8 bright black.
#
# Syntax follows Dave Eddy's bash highlighting (bat --theme base16, as on style.ysap.sh):
# keywords magenta, builtins cyan, function names blue, strings green, comments bright black,
# external commands, variables and punctuation in the default foreground.

ble-face -s argument_error            'fg=0,bg=1'
ble-face -s argument_option           'italic'
ble-face -s auto_complete             'fg=8,italic'
ble-face -s cmdinfo_cd_cdpath         'fg=4,italic'
ble-face -s command_alias             'fg=6'
ble-face -s command_builtin           'fg=6'
ble-face -s command_directory         'fg=4'
ble-face -s command_file              'none'
ble-face -s command_function          'fg=4'
ble-face -s command_keyword           'fg=5'
ble-face -s disabled                  'fg=8'
ble-face -s filename_directory        'fg=4'
ble-face -s filename_directory_sticky 'fg=0,bg=2'
ble-face -s filename_executable       'fg=2,bold'
ble-face -s filename_ls_colors        'none'
ble-face -s filename_orphan           'fg=1,bold'
ble-face -s filename_other            'none'
ble-face -s filename_setgid           'fg=0,bg=3,underline'
ble-face -s filename_setuid           'fg=0,bg=1,underline'
ble-face -s menu_filter_input         'fg=0,bg=3'
ble-face -s overwrite_mode            'fg=0,bg=6'
ble-face -s prompt_status_line        'reverse'
ble-face -s region                    'reverse'
ble-face -s region_insert             'reverse'
ble-face -s region_match              'fg=0,bg=3'
ble-face -s region_target             'fg=0,bg=5'
ble-face -s syntax_brace              'none'
ble-face -s syntax_command            'none'
ble-face -s syntax_comment            'fg=8'
ble-face -s syntax_delimiter          'none'
ble-face -s syntax_document           'fg=2'
ble-face -s syntax_document_begin     'fg=2,bold'
ble-face -s syntax_error              'fg=0,bg=1'
ble-face -s syntax_escape             'fg=5'
ble-face -s syntax_expr               'fg=4'
ble-face -s syntax_function_name      'fg=4'
ble-face -s syntax_glob               'fg=3'
ble-face -s syntax_history_expansion  'fg=5,italic'
ble-face -s syntax_param_expansion    'none'
ble-face -s syntax_quotation          'fg=2'
ble-face -s syntax_tilde              'fg=4'
ble-face -s syntax_varname            'none'
ble-face -s varname_array             'none'
ble-face -s varname_empty             'fg=8'
ble-face -s varname_export            'bold'
ble-face -s varname_expr              'none'
ble-face -s varname_hash              'none'
ble-face -s varname_number            'none'
ble-face -s varname_readonly          'bold'
ble-face -s varname_transform         'none'
ble-face -s varname_unset             'fg=0,bg=1'
ble-face -s vbell_erase               'bg=8'
