---
- name: Configure vivid
  hosts: localhost

  vars:
    vivid_home: "{{ ansible_env.HOME }}/.vivid"

  tasks:
    - name: install vivid
      community.general.homebrew:
        name: vivid

    - name: Link vivid directory
      ansible.builtin.file:
        src: "{{ ansible_env.PWD }}/../../vivid"
        dest: "{{ ansible_env.HOME }}/.vivid"
        state: link
        force: true
