---
- name: Configure scripts
  hosts: localhost

  tasks:
    - name: Ensure scripts directorie
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ ansible_env.HOME }}/.scripts"

    - name: Link bin scripts
      file:
        src: "{{ ansible_env.PWD }}/../../scripts"
        dest: "{{ ansible_env.HOME }}/.scripts"
        state: link
        force: true

