-- Personal keybinding overrides. Omarchy's defaults come from require("default.hypr.omarchy")
-- in hyprland.lua; unbind a default before replacing it. List everything with:
--   omarchy menu keybindings --print
