- name: Download and install Nerd Fonts
  include_tasks: download.yml
  loop:
    - FiraCode
    - DejaVuSansMono
    - JetBrainsMono
    - FantasqueSansMono
    - VictorMono
    - SourceCodePro
    - Hack

- name: Install Google Roboto Fonts via Homebrew
  community.general.homebrew:
    name:
      - font-roboto
